### ISSUE TITLE
[Assignment] - TODO markup

### ISSUE THREAD

**Issue by arch-spatula** [arch-spatula/wanted-pre-onboarding-frontend#19]
# TODO markup

[과제 링크](https://github.com/walking-sunset/selection-task#assignment-5)

- [x] `/todo`경로에 접속하면 투두 리스트의 목록을 볼 수 있도록 해주세요
- [x] 목록에서는 TODO의 내용과 완료 여부가 표시되어야 합니다.
- [x] TODO의 완료 여부는 `<input type="checkbox" />`를 통해 표현해주세요
- [x] TODO는 `<li>` tag를 이용해 감싸주세요

---

- [ ] ~~`CustomInput`에서 `checkbox`, `color` type제거~~
- [x] `CustomCheckBox` 컴포넌트 구현하기
- [x] `d.ts`에 `todo` 추가
- [x] `TodoList` 컴포넌트 구현
- [x] `TodoItem` 컴포넌트 구현

**Comment by arch-spatula** [comment]
CustomInput에서 checkbox, color type는 시간당 가치가 낮기 때문에 후순위로 미룹니다.

**Comment by arch-spatula** [comment]
```text
feat/todo-markup
```

```sh
git checkout -b "feat/todo-markup"
```

**Comment by arch-spatula** [comment]
refactor: custom
